In [1]:
# Import Library
import pandas as pd
import numpy as np

In [2]:
# Read all the csv Data
data = pd.read_csv('./Encoded_Data.csv')

In [3]:
# Show the first few rows
data.head()

,Age,Biomass_Fuel_Exposure,Occupational_Exposure,Family_History_COPD,BMI,Air_Pollution_Level,Respiratory_Infections_Childhood,COPD_Diagnosis,Gender_Male,Smoking_Status_Former,Smoking_Status_Never,Location_Biratnagar,Location_Butwal,Location_Chitwan,Location_Dharan,Location_Hetauda,Location_Kathmandu,Location_Lalitpur,Location_Nepalgunj,Location_Pokhara
0,-1.602656,1.012073,0.966559,0.992032,0.182927,-0.784912,-0.972381,0,True,True,False,False,False,False,False,False,False,True,False,False
1,0.331228,1.012073,-1.034598,-1.008032,0.754353,-0.077974,1.028403,0,True,False,True,False,False,False,False,False,False,False,False,True
2,-1.469285,-0.988071,-1.034598,0.992032,0.368536,-0.198304,1.028403,0,True,True,False,False,False,False,False,False,False,False,False,True
3,-1.269228,1.012073,-1.034598,-1.008032,0.168329,1.757056,-0.972381,1,False,False,False,False,False,False,False,False,True,False,False,False
4,0.197856,-0.988071,-1.034598,-1.008032,-0.248770,-0.288551,1.028403,0,True,False,True,False,False,False,False,False,False,False,False,True

In [4]:
# Create Interaction Terms
data['Gender_Smoking'] = data['Gender_Male'] * data['Smoking_Status_Former'] * data['Smoking_Status_Never']

In [5]:
# Log Transformation for Air_Pollution_Level and BMI
data['Air_Pollution_Level_log'] = data['Air_Pollution_Level'].apply(lambda x: np.log1p(x))  # log1p to handle zeroes
data['BMI_log'] = data['BMI'].apply(lambda x: np.log1p(x))

# Age Binning
bins = [0, 18, 40, 60, 100]
labels = ['Young', 'Adult', 'Middle_Aged', 'Elderly']
data['Age_Bin'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)
data_encoded = pd.get_dummies(data, columns=['Age_Bin'], drop_first=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_13008\441645331.py:2: RuntimeWarning: invalid value encountered in log1p
  data['Air_Pollution_Level_log'] = data['Air_Pollution_Level'].apply(lambda x: np.log1p(x))  # log1p to handle zeroes
C:\Users\Dell\AppData\Local\Temp\ipykernel_13008\441645331.py:3: RuntimeWarning: invalid value encountered in log1p
  data['BMI_log'] = data['BMI'].apply(lambda x: np.log1p(x))

In [6]:
# Save the data after feature Engineering
data_encoded.to_csv('../Prediction/COPD_Data_Engineered.csv', index=False, encoding='utf-8')